model:
  path: artifacts/ssdlite_mobiledet_car_v2_edgetpu.tflite
  # path: artifacts/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
  # path: artifacts/ssd_mobilenet_v2_coco_quant_postprocess_edgetpu.tflite
  # path: artifacts/yolov8n_edge_tpu_int8.tflite.tflite
  type: 'SSD'

input:
  shape: [1, 320, 320, 3]
  preprocessing:
    normalization: [-128, 127] 
    dtype: uint8
  tensor_id: 0

output:
  label_file_path: artifacts/car_labels.txt
  tensor_id: [47]
  postprocessing:
    confidence_threshold: 0.5
    iou_threshold: 0.5
    top_k: 0.4
    dtype: uint8
    quantization:
      scales: 0.0078125
      zero_point: 255
      type: float32

metrics:
   accuracy_threshold: 0.80