
model:
  path: artifacts/ssdlite_mobiledet_coco_qat_postprocess_edgetpu.tflite
  type: 'SSD'

input:
  shape: [1, 320, 320, 3]
  preprocessing:
    normalization: [-128, 127] 
    dtype: uint8
  tensor_id: 0

output:
  label_file_path: artifacts/coco_labels.txt
  tensor_id: [47]
  postprocessing:
    confidence_threshold: 0.6
    iou_threshold: 0.5
    top_k: 0.5
    dtype: uint8
    quantization:
      scales: 0.003986024297773838
      zero_point: -128
      type: float32

metrics:
   accuracy_threshold: 0.80
